repos:
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]
      exclude: migrations/.*
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: migrations/.*
  - id: trailing-whitespace
    exclude: migrations/.*
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    name: black
    args: [--check, --diff, --skip-string-normalization]
    exclude: migrations/.*
