# Generated by Django 4.2 on 2023-07-21 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("document_manager", "0008_alter_document_batch_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="batch_id",
        ),
        migrations.DeleteModel(
            name="Batch",
        ),
    ]
