# Generated by Django 4.2 on 2023-07-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_manager", "0011_remove_document_batch_id_document_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="number",
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
