# Generated by Django 4.2 on 2023-05-12 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Confidentiality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_interno", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "id_expediente",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "blockchain_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("descripcion_documento", models.CharField(max_length=1000)),
                (
                    "descripcion_expediente",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("created_at", models.DateTimeField()),
                ("modified_at", models.DateTimeField()),
                ("esta_activo", models.BooleanField(default=True)),
                (
                    "confidencialidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document_manager.confidentiality",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Edificio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_estado", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="InternalArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoDeDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Foja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_lote", models.IntegerField()),
                ("id_interno", models.IntegerField()),
                ("imagen", models.TextField()),
                ("data", models.JSONField()),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document_manager.documento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=255, unique=True)),
                ("number", models.IntegerField()),
                ("code", models.ImageField(upload_to="images/")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("modified_at", models.DateField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="document_manager.internalarea",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="documento",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.estado",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="etiqueta",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.etiqueta",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="tipo_documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.tipodedocumento",
            ),
        ),
        migrations.CreateModel(
            name="DocumentLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_salida", models.DateField()),
                ("id_caja", models.IntegerField()),
                (
                    "edificio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document_manager.edificio",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document_manager.nivel",
                    ),
                ),
            ],
        ),
    ]
