# Generated by Django 4.2 on 2023-05-30 22:04

import datetime
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("document_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
                ),
                (
                    "file_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de expediente",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "blockchain_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("document_description", models.CharField(max_length=1000)),
                (
                    "file_description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("created_at", models.DateTimeField()),
                ("modified_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255, unique=True)),
                ("number", models.IntegerField()),
                ("bar_code_image", models.ImageField(upload_to="images/")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("modified_at", models.DateField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="document_manager.internalarea",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.IntegerField(help_text="ID de Lote")),
                ("intern_id", models.IntegerField(help_text="ID propio si lo tiene")),
                ("image", models.TextField()),
                ("data", models.JSONField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document_manager.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="etiqueta",
            name="area",
        ),
        migrations.RemoveField(
            model_name="etiqueta",
            name="user",
        ),
        migrations.RemoveField(
            model_name="foja",
            name="documento",
        ),
        migrations.RemoveField(
            model_name="confidentiality",
            name="nivel",
        ),
        migrations.RemoveField(
            model_name="documentlocation",
            name="edificio",
        ),
        migrations.RemoveField(
            model_name="documentlocation",
            name="fecha_inicio",
        ),
        migrations.RemoveField(
            model_name="documentlocation",
            name="fecha_salida",
        ),
        migrations.RemoveField(
            model_name="documentlocation",
            name="id_caja",
        ),
        migrations.RemoveField(
            model_name="documentlocation",
            name="nivel",
        ),
        migrations.AddField(
            model_name="confidentiality",
            name="level",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentlocation",
            name="box_id",
            field=models.IntegerField(help_text="ID caja que contiene el documento", null=True),
        ),
        migrations.AddField(
            model_name="documentlocation",
            name="init_date",
            field=models.DateField(
                default=datetime.datetime.now,
                help_text="Fecha en la que ingresa el documento",
            ),
        ),
        migrations.AddField(
            model_name="documentlocation",
            name="out_date",
            field=models.DateField(help_text="Fecha en la que se retira el documento", null=True),
        ),
        migrations.DeleteModel(
            name="Documento",
        ),
        migrations.DeleteModel(
            name="Edificio",
        ),
        migrations.DeleteModel(
            name="Estado",
        ),
        migrations.DeleteModel(
            name="Etiqueta",
        ),
        migrations.DeleteModel(
            name="Foja",
        ),
        migrations.DeleteModel(
            name="Nivel",
        ),
        migrations.DeleteModel(
            name="TipoDeDocumento",
        ),
        migrations.AddField(
            model_name="document",
            name="confidentiality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.confidentiality",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.documenttype",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="label",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="document_manager.label"),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.status",
            ),
        ),
        migrations.AddField(
            model_name="documentlocation",
            name="building",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.building",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentlocation",
            name="level",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.level",
            ),
            preserve_default=False,
        ),
    ]
