# Generated by Django 4.2 on 2023-07-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_manager", "0003_batch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="id",
        ),
        migrations.AlterField(
            model_name="batch",
            name="number",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
