# Generated by Django 4.2 on 2023-07-21 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("document_manager", "0004_remove_batch_id_alter_batch_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Batch",
        ),
    ]
