# Generated by Django 4.2 on 2023-07-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("document_manager", "0006_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="batch_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.batch",
            ),
        ),
    ]
