# Generated by Django 4.2 on 2023-07-21 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_manager", "0010_batch_document_batch_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="batch_id",
        ),
        migrations.AddField(
            model_name="document",
            name="batch",
            field=models.ForeignKey(
                default=1,
                help_text="ID de lote",
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.batch",
            ),
            preserve_default=False,
        ),
    ]
