# Generated by Django 4.2 on 2023-07-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("document_manager", "0013_alter_sheet_batch_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_status_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="batch",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.batchstatus",
            ),
        ),
    ]
