# Generated by Django 4.2 on 2023-07-27 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("document_manager", "0014_batchstatus_alter_batch_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Status",
            new_name="DocumentStatus",
        ),
    ]
