# Generated by Django 4.2 on 2023-08-04 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_manager", "0016_rename_batch_status_name_batchstatus_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="document_manager.batchstatus",
            ),
        ),
    ]
