# Generated by Django 4.2 on 2023-08-08 11:33

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("document_manager", "0017_alter_batch_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, unique=True)),
                (
                    "init_date",
                    models.DateField(
                        default=datetime.datetime.now,
                        help_text="Fecha en la que ingresa el documento",
                    ),
                ),
                (
                    "out_date",
                    models.DateField(
                        help_text="Fecha en la que se retira el documento", null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.TextField(help_text="Imagen escaneada en base64")),
                (
                    "data",
                    models.JSONField(help_text="Contenido Bruto de la digitalizacion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, unique=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document_manager.level",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, unique=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelves",
                        to="document_manager.room",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="document",
            name="blockchain_token",
        ),
        migrations.RemoveField(
            model_name="document",
            name="file_description",
        ),
        migrations.RemoveField(
            model_name="document",
            name="file_id",
        ),
        migrations.RemoveField(
            model_name="label",
            name="area",
        ),
        migrations.AddField(
            model_name="document",
            name="internal_area",
            field=models.ForeignKey(
                help_text="Area Interna",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="document_manager.internalarea",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="batch",
            field=models.ForeignKey(
                help_text="ID de Lote",
                on_delete=django.db.models.deletion.PROTECT,
                to="document_manager.batch",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="confidentiality",
            field=models.ForeignKey(
                blank=True,
                help_text="Nivel de Confidencialidad",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="document_manager.confidentiality",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_description",
            field=models.CharField(
                default="", help_text="Descripcion del Documento", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de Documento",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="document_manager.documenttype",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="internal_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Numero de Expediente",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="label",
            field=models.OneToOneField(
                blank=True,
                help_text="Etiqueta",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="document_manager.label",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.ForeignKey(
                help_text="Estado del Documento",
                on_delete=django.db.models.deletion.PROTECT,
                to="document_manager.documentstatus",
            ),
        ),
        migrations.DeleteModel(
            name="Sheet",
        ),
        migrations.AddField(
            model_name="page",
            name="document",
            field=models.ForeignKey(
                help_text="Documento al que pertenece",
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.document",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="label",
            field=models.OneToOneField(
                help_text="Etiqueta de la Foja",
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.label",
            ),
        ),
        migrations.AddField(
            model_name="documentstatushistory",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.document",
            ),
        ),
        migrations.AddField(
            model_name="documentstatushistory",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="document_manager.documentstatus",
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="shelf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boxes",
                to="document_manager.shelf",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="box",
            field=models.ForeignKey(
                blank=True,
                help_text="Caja",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="document_manager.box",
            ),
        ),
    ]
