# Generated by Django 4.2 on 2023-08-10 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_manager", "0018_box_documentstatushistory_page_room_shelf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.ForeignKey(
                blank=True,
                help_text="Estado del Documento",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="document_manager.documentstatus",
            ),
        ),
    ]
